version: '3.7'
services:
    jenkins:
      build: .
      image: jenkins-docker:1.0.0
      restart: always
      container_name: jenkins
      environment:
        - JENKINS_OPTS="--prefix=/jenkins"
        - CASC_JENKINS_CONFIG=/var/jenkins_conf
        - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      volumes:
        - ./jenkins_home:/var/jenkins_home
        - ./casc_configs:/var/jenkins_conf
        - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
        - 80:8080
