version: '3.7'
services:
    jenkins:
      image: jenkins-docker:1.0.0
      restart: always
      container_name: jenkins
      environment:
        - JENKINS_OPTS="--prefix=/jenkins"
      volumes:
        - ./jenkins_home:/var/jenkins_home
        - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
        - 80:8080
